(setq ispell-program-name "aspell.exe")
(setq tramp-default-method "plink")
(setq-default epg-gpg-program "~/AeroFS/gpg/gpg.exe")
(setq ps-printer-name "BULLZIP")
(setq ps-printer-name-option "-P")
(setq ps-lpr-command "c:/cygwin/bin/lpr.exe")
